apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: bpsapp
  name: bpsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: bpsapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: bpsapp
    spec:
      containers:
        - image: bryanstrader/bps-client:0.2
          name: bpsapp
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
