services: 
    bpsapi:
        image: bryanstrader/bps-server:0.2
        ports:
        - "5000:5000"

    bpsapp:
        image: bryanstrader/bps-client:0.2
        links:
        - bpsapi
        ports:
        - "3000:3000"