version: "2"
services: 
    bpsapi:
        image: bryanstrader/bps-server:0.7
        ports:
            - "5007:5007"
    bpsapp:
        image: bryanstrader/bps-client:0.7
        links:
            - bpsapi
        ports:
            - "3000:3000"